development: &default
  adapter: postgresql
  encoding: unicode
  database: codeskull_dev
  pool: 5
  username: postgres
  password:
  host: db

test: &test
  <<: *default
  database: codesull_test

production:
  <<: *default
  database: codeskull_production
  username: codeskull
  password: <%= ENV['CODESKULL_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test